language: node_js
node_js:
  - "6.3.1"

before_script:
  - npm install

script:
  - npm run webpack
  - npm test

after_script:
  - npm install codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info

git:
  depth: 10
